id: P005509
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W22097
  title: གངས་ལྗོངས་མི་རིགས་ཁག་གི་འབྲེལ་བ་བརྗོད་པ་གཟུར་གནས་ཡིད་ཀྱི་དགའ་སྟོན།
  author: ''
  volumes:
    285d8412f9a24758af8416c1e1f41538:
      image_group_id: I1KG24083
      title: ''
      volume_number: 1
      total_pages: 188
      base_file: v001.txt
